# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Ulysses's blog
url:                 https://ulysseswolf.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  email:             ulysseswolf@gmail.com

