# Site settings
title: Ulysses

owner:
  name: Brett Stevenson # or company name
  email: ulysseswolf@gmail.com

first_published: 2015 # if migrating another site, the year of your first publish
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

social:
  github: https://github.com/ulysseswolf
 

# If you have custom extensions, specifically includes/_my/custom.scss,
# set this to yes
custom_extensions: no


# Build settings
permalink: /:categories/:title.html

# permalink: /:title.html
markdown: kramdown
highlighter: rouge
sass:
 style: compressed
exclude: ['README.md','Gulpfile.js','.sass-lint.yml','package.json','node_modules', 'jspm_packages','fonts/*.html']
include: ['_pages','.htaccess']
defaults:
  - scope:
      path: _pages
    values:
      layout: page

html_proofer:
  check_favicon: true
  check_html: true
  allow_hash_href: true
  http_status_ignore: [999,522,403]
  file_ignore:
    - bower_components/*
    - bower_components/**/*.html
    - fonts/*

# to initialize arrays in assignments (assign myarr = site.empty_array)
# (easier to grok than assign myarr = '' | split',')
empty_array: []
